spring:
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://pcs-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: login
          uri: lb://pcs-auth
          predicates:
            - Path=/login/**