spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://pcs-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1