spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: auth
          uri: lb://pcs-auth
          predicates:
            - Path=/auth/**
          filters:
            - StripPrefix=1
        - id: general
          uri: lb://pcs-general
          predicates:
            - Path=/general/**
          filters:
            - StripPrefix=1
        - id: addresses
          uri: lb://pcs-general
          predicates:
            - Path=/addresses

